name: Update CricHD Playlist

on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:

jobs:
  update-crichd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Fetch CricHD.m3u
      run: |
        curl -sL -o CricHD.m3u "https://iptv-scraper-zilla.pages.dev/CricHD.m3u"

    - name: Convert M3U to JSON
      run: |
        python - <<'EOF'
        import re, json

        with open("CricHD.m3u", "r", encoding="utf-8") as f:
            m3u = f.read().strip().splitlines()

        channels = []
        for i in range(len(m3u)):
            if m3u[i].startswith("#EXTINF"):
                logo = re.search(r'tvg-logo="(.*?)"', m3u[i])
                group = re.search(r'group-title="(.*?)"', m3u[i])
                title = m3u[i].split(",")[-1].strip()
                stream_url = m3u[i + 1] if i + 1 < len(m3u) else ""
                channels.append({
                    "id": "(no tvg-id)",
                    "title": title,
                    "group_title": group.group(1) if group else "",
                    "logo_url": logo.group(1) if logo else "",
                    "stream_url": stream_url,
                    "license_url": "",
                    "user_agent": "",
                    "cookie": ""
                })

        with open("CricHD.json", "w", encoding="utf-8") as f:
            json.dump(channels, f, indent=2)
        EOF

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git add CricHD.m3u CricHD.json
        git commit -m "Auto-update CricHD playlist and JSON" || echo "No changes to commit"

        git fetch origin main
        git rebase origin/main || git rebase --skip
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
