name: Update CricHD Playlist

on:
  schedule:
    - cron: "*/20 * * * *"   # every 20 minutes
  workflow_dispatch:

jobs:
  update-crichd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Fetch CricHD.m3u
      run: |
        curl -sL -o CricHD.m3u "https://iptv-scraper-zilla.pages.dev/CricHD.m3u"

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git add CricHD.m3u
        git commit -m "Auto-update CricHD.m3u" || echo "No changes to commit"

        git fetch origin main
        git rebase origin/main || git rebase --skip
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
