name: Update Channels JSON

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */11 * * *'   # Runs every 11 hours

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch required files
      run: |
        curl -s -o jio_cookie.txt ${{ secrets.JIO_COOKIE_URL }}
        curl -s -o zee_hdntl.txt ${{ secrets.ZEE_HDNTL_URL }}
        curl -s -o epg_url.txt ${{ secrets.EPG_URL }}

    - name: Update JSON with new tokens and EPG URL
      run: |
        jio_cookie=$(cat jio_cookie.txt)
        zee_hdntl=$(cat zee_hdntl.txt)
        epg_url=$(cat epg_url.txt)

        jq --arg epg "$epg_url" --arg jio "$jio_cookie" --arg zee "$zee_hdntl" '
          {
            epg_url: $epg,
            channels: (
              .[] | map(
                if (.stream_url | test("jiotvmblive.cdn.jio.com")) then
                  .cookie = $jio |
                  .stream_url |= sub("__hdnea__=[^&]*"; $jio) |
                  .stream_url |= sub("cookie=__hdnea__=[^&]*"; "cookie=" + $jio)
                elif (.stream_url | test("zee5.com")) then
                  .cookie = $zee |
                  .stream_url |= sub("hdntl=[^&]*"; $zee)
                else
                  .
                end
              )
            )
          }
        ' full_channels.json > temp.json && mv temp.json full_channels.json

    - name: Commit and Push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add full_channels.json
        git commit -m "Auto-update tokens & EPG URL"
        git push
